### ISSUE TITLE
Problem with Installing Understat package

### ISSUE THREAD

**Issue by SoccerCashUK** [nickpadd/EuropeanFootballLeaguePredictor#63]
Hi having major problem trying to install understat by pip
James

**Comment by nickpadd** [comment]
Hello! Did you attempt to install all the dependencies  yourself?

I suggest using Poetry or the requirements.txt/pip as it is explained in the README.md because they specify the package versions and help avoid conflicts.

Can you please provide me with the error message that appears while installing?

**Comment by nickpadd** [comment]
Same as #80
